// 니스 분류 (Nice Classification) 45개 코드
// 출처: https://www.kipo.go.kr/ko//niceIntlGoodsSortMng.do?sysCd=SCD02&menuCd=SCD0201116&parntMenuCd2=SCD0201114&pgmId=PGM0000048 변형

export const NICE_CODES = [
  { code: "", label: "전체" }, // 기본값: 필터 안 함
  { code: "01", label: "화학제품" },
  { code: "02", label: "페인트, 도료" },
  { code: "03", label: "세제, 화장품" },
  { code: "04", label: "공업용 오일, 양초" },
  { code: "05", label: "약제" },
  { code: "06", label: "비금속 재료" },
  { code: "07", label: "기계" },
  { code: "08", label: "수공구" },
  { code: "09", label: "전자기기, 컴퓨터" },
  { code: "10", label: "의료기기" },
  { code: "11", label: "조명, 가전" },
  { code: "12", label: "운송장치" },
  { code: "13", label: "화기, 폭약" },
  { code: "14", label: "보석, 시계" },
  { code: "15", label: "악기" },
  { code: "16", label: "종이, 문구" },
  { code: "17", label: "고무, 플라스틱" },
  { code: "18", label: "가죽, 가방" },
  { code: "19", label: "비금속 건축재료" },
  { code: "20", label: "가구" },
  { code: "21", label: "가정용품" },
  { code: "22", label: "로프, 그물" },
  { code: "23", label: "실, 사" },
  { code: "24", label: "직물" },
  { code: "25", label: "의류, 신발" },
  { code: "26", label: "레이스, 단추" },
  { code: "27", label: "카펫, 매트" },
  { code: "28", label: "완구, 운동용품" },
  { code: "29", label: "식육, 가공식품" },
  { code: "30", label: "곡물, 빵, 차, 커피" },
  { code: "31", label: "농축산물, 곡물" },
  { code: "32", label: "맥주, 음료" },
  { code: "33", label: "알코올 음료" },
  { code: "34", label: "담배" },
  { code: "35", label: "광고, 사업관리" },
  { code: "36", label: "보험, 금융" },
  { code: "37", label: "건설, 수리" },
  { code: "38", label: "통신" },
  { code: "39", label: "운수, 여행" },
  { code: "40", label: "재료처리" },
  { code: "41", label: "교육, 오락, 스포츠" },
  { code: "42", label: "과학기술, IT 디자인" },
  { code: "43", label: "음식점업" },
  { code: "44", label: "의료, 미용, 농업" },
  { code: "45", label: "법률, 보안 서비스" },
];
