from datetime import datetime
from typing import List, Optional

from pydantic import BaseModel, Field


class PlagiarismExplanation(BaseModel):
    summary: str = Field(..., description="Result summary")
    image_contribution_pct: Optional[float] = Field(None, description="Image contribution percent")
    text_contribution_pct: Optional[float] = Field(None, description="Text contribution percent")
    name_contribution_pct: Optional[float] = Field(None, description="Trademark name contribution percent")
    description_contribution_pct: Optional[float] = Field(None, description="Description contribution percent")
    keyword_matched: List[str] = Field(default_factory=list, description="Matched keywords")
    image_reason: Optional[str] = Field(None, description="Image-based detection reason")
    text_reason: Optional[str] = Field(None, description="Text-based detection reason")
    llm_generated: bool = Field(False, description="Whether the reason was generated by LLM")


class PlagiarismDetectionItem(BaseModel):
    trademark_id: int
    trademark_name: str
    application_number: str
    applicant_name: Optional[str]
    application_date: Optional[str]
    image_url: str
    similarity_score: float = Field(..., example=85.4)
    text_score: Optional[float] = Field(None, description="DB text score")
    image_score: Optional[float] = Field(None, description="DB image score")
    explanation: PlagiarismExplanation


class PlagiarismDetectionResponse(BaseModel):
    history_id: int
    requested_at: datetime
    total_found: int
    highest_similarity: float = Field(..., description="Highest similarity")
    result_summary_text: str = Field(..., description="Overall summary")
    results: List[PlagiarismDetectionItem]


class DetectionHistoryResultItem(BaseModel):
    trademark_id: int
    title: Optional[str] = None
    applicant_name: Optional[str] = None
    application_date: Optional[str] = None
    application_status: Optional[str] = None
    image_url: Optional[str] = None
    similarity_score: float = 0.0
    text_score: Optional[float] = None
    image_score: Optional[float] = None


class DetectionHistoryItem(BaseModel):
    id: int
    type: str = "search"
    title: str
    description: str
    time: str
    downloadable: bool = True
    image_path: Optional[str] = None
    image_url: Optional[str] = None
    history_id: Optional[int] = None
    total_found: int = 0
    highest_similarity: float = 0.0
    input_text: Optional[str] = None
    results: List[DetectionHistoryResultItem] = Field(default_factory=list)
